apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate-job
  labels:
    {{- include "sre-app.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
        - name: migrate-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DATABASE_URL
              value: "{{ .Values.env.DATABASE_URL }}"
            - name: POOL_SIZE
              value: "{{ .Values.env.POOL_SIZE }}"
            - name: SECRET_KEY_BASE
              value: "{{ .Values.env.SECRET_KEY_BASE }}"
            - name: PHX_HOST
              value: "{{ .Values.env.PHX_HOST }}"
            - name: PORT
              value: "{{ .Values.env.PORT }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command: ["/bin/sh", "-c"]
           #args: ["migrate"]
          args: ["echo 'Migrating db!' > /app/bin/sumit"]
      restartPolicy: Never
